In [10]:
from datascience import *
import numpy as np

%matplotlib inline
import matplotlib.pyplot as plots
plots.style.use('fivethirtyeight')

## Numbers ##

Textbook section 4.1

In [11]:
3 * 30 # int

90

In [12]:
10 / 3 # float

3.3333333333333335

In [13]:
3 / 3 # float

1.0

In [14]:
10 ** 3 # 10 * 10 * 10 

1000

In [15]:
10 ** 0.5 # float

3.1622776601683795

In [16]:
12345678 ** 890

ValueError: Exceeds the limit (4300 digits) for integer string conversion; use sys.set_int_max_str_digits() to increase the limit

In [17]:
75892745.215489247589274985712 - 75892745.21548925

0.0

In [18]:
10 / 5

2.0

In [19]:
int(10 / 5)

2

In [20]:
16 / 30

0.5333333333333333

In [21]:
round(16 / 30), int(16 / 30)

(1, 0)

In [22]:
float(3)

3.0

## Strings ##

Textbook section 4.2

In [23]:
'Flavor'

'Flavor'

In [24]:
"Flavor"

'Flavor'

In [25]:
Flavor

NameError: name 'Flavor' is not defined

In [ ]:
'straw' + 'berry'

'strawberry'

In [ ]:
5 + '5'

TypeError: unsupported operand type(s) for +: 'int' and 'str'

In [ ]:
5 + int('5')

10

In [ ]:
'yelp review: ' + str(10)

In [ ]:
str(int('10'))

## Arrays ##

Textbook section 5.1

In [ ]:
my_array = make_array(1, 2, 3)
my_array

array([1, 2, 3])

In [ ]:
type(my_array)

numpy.ndarray

In [ ]:
len(my_array)

3

In [ ]:
# Add a constant value to each element of the array
my_array + 2

array([3, 4, 5])

In [ ]:
# Just like with tables, the original array is not modified
my_array

array([1, 2, 3])

In [ ]:
# Store the resulting array in a new variable if you want to use it later
my_array_plus_two = my_array + 2
my_array_plus_two

array([3, 4, 5])

In [ ]:
my_array * 2

array([2, 4, 6])

In [ ]:
my_array ** 2

array([1, 4, 9])

In [ ]:
my_array_2 = make_array(-1, -2, -1)
my_array_2

array([-1, -2, -1])

In [ ]:
# Adding two arrays adds them together term by term
my_array_2 + my_array

array([0, 0, 2])

In [ ]:
my_array_3 = make_array(1,2,3,4)
my_array_3

array([1, 2, 3, 4])

In [ ]:
my_array + my_array_3

ValueError: operands could not be broadcast together with shapes (3,) (4,) 

In [ ]:
names_array = make_array('Andrew', 'Conan', 'Jonathan')
names_array

array(['Andrew', 'Conan', 'Jonathan'],
      dtype='<U8')

In [ ]:
# .item accesses individual items in the array
names_array.item(0)

'Andrew'

In [ ]:
names_array.item(1)

'Conan'

In [ ]:
names_array.item(3)

IndexError: index 3 is out of bounds for axis 0 with size 3

### Practice 1

The past weeks temperatures in Fahrenheit were:
70, 68, 66, 71, 72, 70, 68

The connection between Fahrenheit temperature F and Celsius temperature C is:
C = 5/9(F - 32)

Use an array calculation to convert all these Fahrenheit temperatures to Celsius.

In [ ]:
temp_array = make_array(70, 68, 66, 71, 72, 70, 68)
cels = (5/9)*(temp_array - 32)


In [ ]:
rounded_cels = np.round(cels,1)
rounded_cels

array([ 21.1,  20. ,  18.9,  21.7,  22.2,  21.1,  20. ])

### Practice 2

A lemonade stand sold
- 50 cups of lemonade at $3.50 each
- 35 bottles of water at $2.00 each
- 25 cookies at $3.00 each

Create an array for sales and an array for cost. Use these to produce a third array for revenue generated by each item (lemonade revenue in the first entry, water revenue in the second, and cookie revenue in the third).

In [ ]:
stand_sales_array = make_array(50, 35, 25)
stand_cost_array = make_array(3.50, 2.00, 3.00)
revenue = stand_sales_array*stand_cost_array
revenue


array([ 175.,   70.,   75.])

In [ ]:
revenue_sum = np.sum(revenue)
revenue_sum

320.0

## Functions on Arrays ##

Textbook section 5.1 (lots more functions there)

In [ ]:
nums = make_array(0, 1, 3, 5, 7)
nums

array([0, 1, 3, 5, 7])

In [ ]:
np.count_nonzero(nums)

4

In [ ]:
np.sum(nums)

16

In [ ]:
np.diff(nums)

array([1, 2, 2, 2])

In [ ]:
np.mean(nums)

3.2000000000000002

In [ ]:
decimals = make_array(1.123, 3.123, 5.123, 7.678)
rounded = np.round(decimals, 2)
rounded

array([ 1.12,  3.12,  5.12,  7.68])

## Improved Practice Problems

In [ ]:
# Round the temperatures


# Sum the revenue


# Ranges

In [ ]:
# One argument gives an array from 0 to the integer provided (excluding right endpoint)
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
# Two arguments denotes the starting value (inclusive) and ending value (exclusive)
np.arange(5, 10)

array([5, 6, 7, 8, 9])

In [27]:
# Three arguments denotes the starting value, ending value, and step size
np.arange(5, 10, 2)


array([5, 7, 9])

# Practice

1. Use arange to generate the following approximation of $\pi$:

$$4 \cdot \left( \left(1 + \frac{1}{5} + \frac{1}{9} + \dots + \frac{1}{9997} \right) - \left(\frac{1}{3} + \frac{1}{7} + \frac{1}{11} + \dots + \frac{1}{9999} \right) \right)$$

- Use arange to generate an array containing 1, 5, 9, ... , 9997
- Use / to generate an array containing 1/1, 1/5, 1/9, ..., 1/9997
- Sum the elements of this array to get the value of the first parenthesis
- Go through a similar process to get the second parenthesis
- Calculuate the estimate

2. Use arange to generate the following approximation of $\pi$:
$$2 \cdot \left( \frac{2}{1} \cdot \frac{4}{3} \cdot \frac{6}{5} \cdots \frac{1,000,000}{999999} \right) \cdot \left( \frac{2}{3} \cdot \frac{4}{5} \cdot \frac{6}{7} \cdots \frac{1,000,000}{1,000,001} \right)$$

In [28]:
#making first array
p1_a1 = np.arange(1,9997,4)
fractions_1 = 1/p1_a1
fractions_1_sum = np.sum(fractions_1)

#making second array
p1_a2 = np.arange(3,9999,4)
fraction_2 = 1/p1_a2
fractions_2_sum = np.sum(fraction_2)

#calculating equation
pi_estimate_1 = 4*((fractions_1_sum) - (fractions_2_sum))
pi_estimate_1

3.1413925735597825

In [32]:
#first array
nume_1 = np.arange(2, 1000000, 2)
denom_1 = np.arange(1, 999999, 2)
nume_denom = nume_1/denom_1
array_1 = np.prod(nume_denom)

#second array
nume_2 = nume_1
denom_2 = np.arange(3,1000001,2)
nume_denom_2 = nume_2/denom_2
array_2 = np.prod(nume_denom_2)

#calculating equation 2
pi_estimate_2 = 2*(array_1)*(array_2)
pi_estimate_2


3.1415910827919729